### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by galacticfr** [dotcypress/ula#10]
git clone git@github.com:dotcypress/ula.git

Cloning into 'ula'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Hi, I encountered this error while following your guidelines, could you fix it please?

**Comment by dotcypress** [comment]
Hey @galacticfr 

You can use HTTPS endpoint for cloning public repos: `git clone https://github.com/dotcypress/ula.git`
